export const SELECTORS = {
  signupName: '[data-qa="signup-name"]',
  signupEmail: '[data-qa="signup-email"]',
  signupButton: '[data-qa="signup-button"]',
  password: '#password',
  createAccountButton: '[data-qa="create-account"]',
  accountCreatedMessage: '[data-qa="account-created"]',
  continueButton: '[data-qa="continue-button"]',
  contactUsLink: 'Contact us',
  contactUsForm: {
    name: '[data-qa="name"]',
    email: '[data-qa="email"]',
    subject: '[data-qa="subject"]',
    message: '[data-qa="message"]',
    uploadFile: 'input[name="upload_file"]',
    submitButton: '[data-qa="submit-button"]',
    successMessage: '.status.alert.alert-success',
  },
  login: {
    signupName: '[data-qa="signup-name"]',
    signupEmail: '[data-qa="signup-email"]',
    signupButton: '[data-qa="signup-button"]',
    password: '#password',
    createAccountButton: '[data-qa="create-account"]',
  },
  contactUs: {
    link: 'Contact us',
    name: '[data-qa="name"]',
    email: '[data-qa="email"]',
    subject: '[data-qa="subject"]',
    message: '[data-qa="message"]',
    uploadFile: 'input[name="upload_file"]',
    submitButton: '[data-qa="submit-button"]',
    successMessage: '.status.alert.alert-success',
  },
};